### ISSUE TITLE
readc3d error

### ISSUE THREAD

**Issue by philjrenaud** [PhilD001/biomechZoo#3]
Hi Phil, 

I am trying to convert some c3d files to zoo, however I am getting the following error:

Reference to non-existent field 'LABELS'.

Error in readc3d (line 182)
    Alabels = cellstr(data.Parameter.ANALOG.LABELS.data');

Error in c3d2zoo (line 90)
    r = readc3d(fl{i});

I tried to test this on some older data and Alabels returns: {''},

thanks for the help

**Comment by PhilD001** [comment]
Hey Phil,

If you are sure that there is nothing wrong with your trials, you can just
edit that line to ignore the labels. Something like:

if isfield(data.Parameter.ANALOG,'LABELS')

put the existing code

end

Can you send me the c3d file? I've since updated the c3d2zoo file so I
would want to check if I get the same error...

**Comment by philjrenaud** [comment]
here ya go, I'll await to see if you get the error or not, thanks


[1489001031032_IHRG]
Philippe Renaud, Research Assistant
mcgill.ca/ihrg, @McGillIHRG
514-398-4184 ext. 0583



________________________________

**Comment by PhilD001** [comment]
sorry file isn't coming through. Pls resend maybe straight to my email

**Comment by PhilD001** [comment]
The updated readc3d and c3d2zoo files solve this bug.
